# Generated by Django 2.2 on 2022-02-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_interviewaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='职级编码')),
                ('level_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='职级名称')),
            ],
            options={
                'verbose_name': '职级表',
                'verbose_name_plural': '职级表',
                'db_table': 'job_level',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeaveReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='离职理由')),
            ],
            options={
                'verbose_name': '离职理由表',
                'verbose_name_plural': '离职理由表',
                'db_table': 'leave_reason',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='dept',
            options={'managed': False, 'verbose_name': '部门列表', 'verbose_name_plural': '部门列表'},
        ),
        migrations.AlterModelOptions(
            name='emp',
            options={'managed': False, 'verbose_name': '员工列表', 'verbose_name_plural': '员工列表'},
        ),
        migrations.AlterModelOptions(
            name='interviewaccount',
            options={'managed': False, 'verbose_name': '员工离职面谈台账', 'verbose_name_plural': '员工离职面谈台账'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'managed': False, 'verbose_name': '岗位列表', 'verbose_name_plural': '岗位列表'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'managed': False, 'verbose_name': '奖金发放记录表', 'verbose_name_plural': '奖金发放记录表'},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'managed': False, 'verbose_name': '奖金标准', 'verbose_name_plural': '奖金标准'},
        ),
    ]
